In [1]:
import pandas as pd 
import numpy as np

In [6]:
#1-dimensional array
a1=np.array([1,2,3])
a1.shape,a1.dtype,a1.ndim,type(a1)

((3,), dtype('int64'), 1, numpy.ndarray)

In [8]:
#2-dimensional array
a2=np.array([[1,2,3],
        [4,5,6]])
a2.shape,a2.dtype,a2.ndim,type(a2)

((2, 3), dtype('int64'), 2, numpy.ndarray)

In [13]:
#3-dimensional array
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])
a3.shape,a3.dtype,a3.ndim,type(a3)

((2, 3, 3), dtype('int64'), 3, numpy.ndarray)

Anatomy of an array

key terms:
Array: a list of numbers, can be multi dimensional
Scaler: a single number
Vector: a list of numbers but 1-dimensional array
Matrix:multi dimensional array

Creation of arrays

In [14]:
simple_array = np.array([1, 2, 3, 4, 5])
simple_array.shape, simple_array.dtype, simple_array.ndim, type(simple_array)

((5,), dtype('int64'), 1, numpy.ndarray)

In [16]:
ones=np.ones((5,2))
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [17]:
zeroes=np.zeros((5,2))
zeroes.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [18]:
#creatting an array within a range of value
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(3,size=(3,3))
random_array

array([[2, 1, 0],
       [2, 1, 1],
       [1, 0, 1]], dtype=int32)

In [24]:
random_array2=np.random.rand(5,3)#random float numbers between 0 and 1
random_array2

array([[0.91400144, 0.80815469, 0.53081213],
       [0.76013893, 0.66731981, 0.71369021],
       [0.45313963, 0.89015435, 0.93025508],
       [0.83702454, 0.18888583, 0.28952026],
       [0.38754853, 0.37208949, 0.73178134]])

Arithmetic

In [25]:
a1

array([1, 2, 3])

In [26]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [27]:
#add 2 arrays
a1+ones

array([2., 3., 4.])

In [28]:
#substract 2 arrays
a1-ones

array([0., 1., 2.])

In [29]:
#multiply 2 arrays
a1*ones

array([1., 2., 3.])

In [30]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [31]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [41]:
a2*a2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
a2+2

array([[3, 4, 5],
       [6, 7, 8]])

In [42]:
a3+a3

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [35]:
a1/ones

array([1., 2., 3.])

In [36]:
a1//ones

array([1., 2., 3.])

In [37]:
a1**2

array([1, 4, 9])

In [38]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081])

In [39]:
a1%2

array([1, 0, 1])

In [40]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])