In [2]:
import pandas as pd 
import numpy as np

In [3]:
#1-dimensional array
a1=np.array([1,2,3])
a1.shape,a1.dtype,a1.ndim,type(a1)

((3,), dtype('int64'), 1, numpy.ndarray)

In [4]:
#2-dimensional array
a2=np.array([[1,2,3],
        [4,5,6]])
a2.shape,a2.dtype,a2.ndim,type(a2)

((2, 3), dtype('int64'), 2, numpy.ndarray)

In [5]:
#3-dimensional array
a3=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],
            [[10,11,12],
            [13,14,15],
            [16,17,18]]])
a3.shape,a3.dtype,a3.ndim,type(a3)

((2, 3, 3), dtype('int64'), 3, numpy.ndarray)

Anatomy of an array

key terms:
Array: a list of numbers, can be multi dimensional
Scaler: a single number
Vector: a list of numbers but 1-dimensional array
Matrix:multi dimensional array

Creation of arrays

In [6]:
simple_array = np.array([1, 2, 3, 4, 5])
simple_array.shape, simple_array.dtype, simple_array.ndim, type(simple_array)

((5,), dtype('int64'), 1, numpy.ndarray)

In [7]:
ones=np.ones((5,2))
ones.astype(int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
zeroes=np.zeros((5,2))
zeroes.astype(int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [9]:
#creatting an array within a range of value
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [10]:
random_array = np.random.randint(3,size=(3,3))
random_array

array([[0, 0, 0],
       [1, 1, 1],
       [2, 0, 2]], dtype=int32)

In [11]:
random_array2=np.random.rand(5,3)#random float numbers between 0 and 1
random_array2

array([[0.36084172, 0.79224864, 0.80395822],
       [0.68758516, 0.88976569, 0.09549738],
       [0.19691802, 0.94768217, 0.03923531],
       [0.56293773, 0.02347517, 0.19110187],
       [0.89508826, 0.13257502, 0.83901604]])

Arithmetic

In [12]:
a1

array([1, 2, 3])

In [13]:
ones=np.ones(3)
ones

array([1., 1., 1.])

In [14]:
#add 2 arrays
a1+ones

array([2., 3., 4.])

In [15]:
#substract 2 arrays
a1-ones

array([0., 1., 2.])

In [16]:
#multiply 2 arrays
a1*ones

array([1., 2., 3.])

In [17]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [18]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [19]:
a2*a2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [20]:
a2+2

array([[3, 4, 5],
       [6, 7, 8]])

In [21]:
a3+a3

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]]])

In [22]:
a1/ones

array([1., 2., 3.])

In [23]:
a1//ones

array([1., 2., 3.])

In [24]:
a1**2

array([1, 4, 9])

In [25]:
np.sqrt(a1)

array([1.        , 1.41421356, 1.73205081])

In [26]:
a1%2

array([1, 0, 1])

In [27]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [28]:
ones=np.ones(3)
ones

array([1., 1., 1.])

Aggregation

In [33]:
massive_array = np.random.random(1000000)
massive_array.size,type(massive_array)

(1000000, numpy.ndarray)

In [34]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

78.2 ms ± 276 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
1 ms ± 68.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [35]:
import random
massive_list=[random.randint(0,20) for i in range(1000000)]
len(massive_list),type(massive_list)

(1000000, list)

In [36]:
%timeit sum(massive_list)
%timeit np.sum(massive_list)

5.14 ms ± 36 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
50.8 ms ± 692 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [37]:
np.mean(a1)

np.float64(2.0)

In [38]:
np.std(a1)

np.float64(0.816496580927726)

In [39]:
np.var(a1)

np.float64(0.6666666666666666)

In [40]:
np.sqrt(np.var(a1))

np.float64(0.816496580927726)

Reshaping

In [41]:
a2.shape

(2, 3)

In [42]:
a2.reshape(2,3,1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

Transpose

In [44]:
a2.transpose(),a2.transpose().shape

(array([[1, 4],
        [2, 5],
        [3, 6]]),
 (3, 2))

In [47]:
matrix=np.random.random(size=(5,3,3))
matrix

array([[[0.14906715, 0.11884061, 0.20949951],
        [0.68533641, 0.75317113, 0.53726161],
        [0.05374702, 0.25690467, 0.60037698]],

       [[0.33527851, 0.99984882, 0.87161594],
        [0.00479491, 0.51733839, 0.28150277],
        [0.04482956, 0.99855317, 0.86464951]],

       [[0.65919389, 0.8571654 , 0.76453658],
        [0.61436606, 0.59154626, 0.2523747 ],
        [0.27103404, 0.58360396, 0.56929097]],

       [[0.38004686, 0.8539553 , 0.83343387],
        [0.1942962 , 0.24440011, 0.78646636],
        [0.51453558, 0.09158942, 0.39944454]],

       [[0.27806825, 0.9494273 , 0.15779712],
        [0.95366733, 0.01241538, 0.48067943],
        [0.72684212, 0.61165013, 0.28352697]]])

In [48]:
matrix.transpose()

array([[[0.14906715, 0.33527851, 0.65919389, 0.38004686, 0.27806825],
        [0.68533641, 0.00479491, 0.61436606, 0.1942962 , 0.95366733],
        [0.05374702, 0.04482956, 0.27103404, 0.51453558, 0.72684212]],

       [[0.11884061, 0.99984882, 0.8571654 , 0.8539553 , 0.9494273 ],
        [0.75317113, 0.51733839, 0.59154626, 0.24440011, 0.01241538],
        [0.25690467, 0.99855317, 0.58360396, 0.09158942, 0.61165013]],

       [[0.20949951, 0.87161594, 0.76453658, 0.83343387, 0.15779712],
        [0.53726161, 0.28150277, 0.2523747 , 0.78646636, 0.48067943],
        [0.60037698, 0.86464951, 0.56929097, 0.39944454, 0.28352697]]])

Dot product

In [50]:
np.random.seed(0)
mat1=np.random.randint(10,size=(3,3))
mat2=np.random.randint(10,size=(3,2))
mat1.shape,mat2.shape

((3, 3), (3, 2))

In [51]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]], dtype=int32)

In [52]:
mat2

array([[4, 7],
       [6, 8],
       [8, 1]], dtype=int32)

In [53]:
np.dot(mat1,mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]], dtype=int32)

In [56]:
mat1@mat2

array([[ 44,  38],
       [126,  86],
       [ 58,  63]], dtype=int32)

In [57]:
mat3=np.random.randint(10,size=(4,3))
mat4=np.random.randint(10,size=(4,3))
mat3.shape,mat4.shape

((4, 3), (4, 3))

In [59]:
np.dot(mat3,mat4.T)

array([[ 53,  89,  48,  67],
       [ 29,  59,  26,  31],
       [ 67, 114,  60,  83],
       [ 27,  17,  13,  33]], dtype=int32)

In [60]:
np.dot(mat3.T,mat4)

array([[ 55, 109,  91],
       [ 40,  83,  32],
       [ 40,  77,  67]], dtype=int32)

Comparing operators

In [62]:
a1>=a2

array([[ True,  True,  True],
       [False, False, False]])

In [63]:
a1>5

array([False, False, False])

Sorting arrays

In [64]:
np.sort(random_array)

array([[0, 0, 0],
       [1, 1, 1],
       [0, 2, 2]], dtype=int32)

In [65]:
np.argsort(random_array)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 0, 2]])

In [66]:
np.argmax(a1)

np.int64(2)

In [67]:
np.argmax(a2)

np.int64(5)

In [69]:
np.argmax(a2,axis=1)

array([2, 2])

In [70]:
np.argmin(a1)

np.int64(0)